"""timestamp

Revision ID: 4c7b829ee0d3
Revises: 9fb66f6b657c
Create Date: 2020-03-23 20:28:02.335494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c7b829ee0d3'
down_revision = '9fb66f6b657c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('bucket', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('link', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('link', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_link_timestamp', table_name='link')
    op.drop_column('link', 'timestamp')
    op.add_column('user', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_updated')
    op.drop_column('user', 'time_created')
    op.add_column('link', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_link_timestamp', 'link', ['timestamp'], unique=False)
    op.drop_column('link', 'time_updated')
    op.drop_column('link', 'time_created')
    op.drop_column('bucket', 'time_updated')
    op.drop_column('bucket', 'time_created')
    # ### end Alembic commands ###
