"""buckte tabel

Revision ID: 87ce4ea5b108
Revises: fe49f0f526a3
Create Date: 2019-10-27 18:06:31.288896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87ce4ea5b108'
down_revision = 'fe49f0f526a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=120), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucket_name'), 'bucket', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bucket_name'), table_name='bucket')
    op.drop_table('bucket')
    # ### end Alembic commands ###
