"""link tabel

Revision ID: 9fb66f6b657c
Revises: 87ce4ea5b108
Create Date: 2019-10-28 20:21:24.007173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9fb66f6b657c'
down_revision = '87ce4ea5b108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_timestamp'), 'link', ['timestamp'], unique=False)
    op.create_index(op.f('ix_link_title'), 'link', ['title'], unique=False)
    op.drop_index('ix_bucket_name', table_name='bucket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bucket_name', 'bucket', ['name'], unique=False)
    op.drop_index(op.f('ix_link_title'), table_name='link')
    op.drop_index(op.f('ix_link_timestamp'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
